// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY73WnTWkFH8sIcknZhJM85usdBqPCGM0',
    appId: '1:1002470773698:web:0e110d8367bc36106efc5b',
    messagingSenderId: '1002470773698',
    projectId: 'testing-fire-auth',
    authDomain: 'testing-fire-auth.firebaseapp.com',
    storageBucket: 'testing-fire-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDArn02CPxsC10TbuQBfKUWXwpaynkpBs4',
    appId: '1:1002470773698:android:33d327acfbc551fc6efc5b',
    messagingSenderId: '1002470773698',
    projectId: 'testing-fire-auth',
    storageBucket: 'testing-fire-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHxgcshj-0GI-CBNySsGe647DJMDQM1ls',
    appId: '1:1002470773698:ios:ed891b53c5a5c83b6efc5b',
    messagingSenderId: '1002470773698',
    projectId: 'testing-fire-auth',
    storageBucket: 'testing-fire-auth.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHxgcshj-0GI-CBNySsGe647DJMDQM1ls',
    appId: '1:1002470773698:ios:ed891b53c5a5c83b6efc5b',
    messagingSenderId: '1002470773698',
    projectId: 'testing-fire-auth',
    storageBucket: 'testing-fire-auth.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY73WnTWkFH8sIcknZhJM85usdBqPCGM0',
    appId: '1:1002470773698:web:6e3cd3063ac4ac346efc5b',
    messagingSenderId: '1002470773698',
    projectId: 'testing-fire-auth',
    authDomain: 'testing-fire-auth.firebaseapp.com',
    storageBucket: 'testing-fire-auth.firebasestorage.app',
  );
}
